version: 2

sources:
  - name: raw
    description: "Raw data from Telegram scraping"
    schema: raw
    tables:
      - name: telegram_messages
        description: "Raw Telegram messages from scraping"
        columns:
          - name: message_id
            description: "Unique message identifier"
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: message_date
            description: "Timestamp of the message"
          - name: message_text
            description: "Text content of the message"
          - name: has_media
            description: "Whether message contains media"
          - name: image_path
            description: "Path to downloaded image"
          - name: views
            description: "Number of views"
          - name: forwards
            description: "Number of forwards"
            
      - name: yolo_detections
        description: "YOLO object detection results"
        columns:
          - name: detection_id
            description: "Unique detection identifier"
          - name: message_id
            description: "Foreign key to message"
          - name: detected_class
            description: "Class of detected object"
          - name: confidence_score
            description: "Confidence score"
          - name: image_category
            description: "Category of image"
